travis:
  secure:
    BINSTAR_TOKEN: Ohzlll/n6J3oLGHIcXFFpfQVIRe6GQazDkzTHCE7MjMtSrzYkXKUvBr45c4ur5hU6eQEtPT8Mz8BlWi1RWKG6eB+Xq7QvUtRNyhqjT60zRZmNV40CsWcBy7mW+CngBiuGqfg24RGmA+gz7gvIxURYRnSmeEMXfOZ1GCM8dTqTVubf93RqLGI4EgZo/4Bxil6ouqRw7THnz/ruVe5Ho+q3+RIztzd5ff5llmrCEhyI8v54u6yb6Lg/jTMyxzP8xp4CzgdmILmd6Pe8rexh2VI6d83WRYbGgi7zhxVcZWOONDLekCrS05w7W1wHE0Z1qym9cKgglhL4V2+sLW43oUwlauQU+jJ7iIjZZZnpbrd0Nym+AnefwEsllevkBo8ruoiNj3H01jeapDRqj2hQM6/lxDj3l4wAVRLz8pfS8BQrhzfmnt5zOc3O5g6OtAJ4OND3JkPNnewQ8TV54O9lvejHxCEIL/yx1n3/xDM2fIKX+8GQxn22pCvAidlZRTnzu8u5cn1GVdy3vg39eTHPnxblc/3rznHcenwKwGLYpKQuAlvwyWi6JOK9/T98RnWgUvP64IANbqtmW+SqCuvF97aKM3NMQea+n5uew9THDc7Y7xwTzHQ1fUW3+9AZBiXvApYU1tD5DE2PVm2wS6CA5giIZ0G6AOK6RZWXmYJnTudU28=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
